### ISSUE TITLE
Minor issue: Lag when breaking blocks when 'switchback' in Substitutor is on.

### ISSUE THREAD

**Issue by mewzurui** [DuelMonster/MinersAdvantage#1]
Greetings,

There is visual lag when breaking blocks (plants are what I was breaking, basically 1 hit while flying). I noticed it only happens when switchback is enabled, works normally (no lagging) otherwise. 

I Hope this is helpful, keep up the good work and have a great day.

~Mew

**Comment by DuelMonster** [comment]
Thanks Mew, I'll look into it.
