### ISSUE TITLE
Request: Adjust Minecraft's Built-In Block Tick Delay

### ISSUE THREAD

**Issue by budgej** [DuelMonster/MinersAdvantage#31]
Hi,

I noticed your mod has settings to adjust Block Tick Delay, but it appears to affect your mod's processes only.  Would it be possible for the setting to also adjust the built-in delay when breaking blocks with vanilla tools?  I have come to rely on the following jar mod, but it has always been hit-or-miss as far as compatibility goes, since I have to use a modified jar.  Having the feature built-in to another mod I think would be much more convenient and compatible.

Thanks for reading.

[Click Mining Fix Mod](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1293388-snapshots-1-8-8-forge-click-mining-fix-fix-remove)

**Comment by DuelMonster** [comment]
This won't be added to MinersAdvantage as it would require MC core modification.
