### ISSUE TITLE
veination ore block id list cleared on startup

### ISSUE THREAD

**Issue by Knito58** [DuelMonster/MinersAdvantage#36]
#### What happens: 
	ores = ["mysticalagriculture:inferium_ore","mysticalagriculture:prosperity_ore"]
becomes 
	ores = []
when starting

vein mining the mystical agriculture ore blocks does not work.

if I omit the quotes there's a startup error like "missing block mysticalagriculture:inferiumore" (underscore missing in error message)

#### What you expected to happen:
no clearing, veination gets the mystical agriculture ores, too.

#### Does this issue occur on a server or single player world?

- [ didnt test that ] Server
- [ x ] Client Only

#### Steps to reproduce:
1. Have mystical agriculture
2. Try to config it
3. 

#### Versions (make sure you are on the latest version before reporting):

- MinersAdvantage: 1.4.2.248
- Forge: 28.1.90
- Minecraft: 1.14.4

#### Crash log:
none

**Comment by DuelMonster** [comment]
Investigations seem to indicate that this may be an issue with forge as all other config value types do not get overridden.

Forge issue: [#6373](https://github.com/MinecraftForge/MinecraftForge/issues/6373)

**Comment by DuelMonster** [comment]
Solution found, waiting release
