### ISSUE TITLE
Crash on mining with Gravitation Suite Drill (Big Holes mode)

### ISSUE THREAD

**Issue by ghost** [DuelMonster/MinersAdvantage#40]
#### Does this issue occur on a server or single player world?

- [ ] Server
- [ x] Client Only

#### Steps to reproduce:
1. Get Gravitation Suite Drill
2. Mine ore with Big Holes mode
3. Crash
4. Ez Beta test for me 🥉 

#### Versions (make sure you are on the latest version before reporting):

- MinersAdvantage: Last
- Forge: last for 1.12.2
- Minecraft: 1.12.2

#### Crash log:

<details><summary>Expand for ---- Minecraft Crash Report ----</summary>

```
https://paste.dimdev.org/gupiyebago.mccrash
https://paste.dimdev.org/qihulewefu.mccrash
```
</details>

**Comment by DuelMonster** [comment]
Crash is within Gravitation Suite not MinersAdvantage 
```
java.lang.NullPointerException
    at com.chocohead.gravisuite.items.ItemAdvancedDrill.getBrokenBlocks(ItemAdvancedDrill.java:123)
```

**Comment by ghost** [comment]
But without mod it works fine

**Comment by DuelMonster** [comment]
Yes I dare say it does, but it is crashing in Gravitation.  Seems to be trying to get blocks after MinersAdvatage has already processed them.  There is nothing I can do to resolve that...

I suggest you raise the issue with them as an "incompatibility with MinersAdvatage" bug.
