### ISSUE TITLE
[Problem]: Lumbination version 243 works, version 244 no longer works

### ISSUE THREAD

**Issue by 0xebjc** [DuelMonster/MinersAdvantage#41]
#### Issue description:
Lumbination doesn't cut high enough or big enough in radius.

#### What happens:
I've set the config in 'common' to radius of 3, and max blocks of 54.  This is because I want the shaftination to work as as 3x3 shaft 6 blocks deep.  But for lumbination, it would be more practical for it to have a radius of 6 or 9, and cut much higher, say 18 blocks high, one of the mods I have creates custom trees, not sure which one, quark, or reccurentcomplex?

The problem is I have a bunch of trees that are taller then 6 blocks high and I'm left with the lumbination leaving the treetops, and eventually when I'm tree farming, I get this huge covered tree canopy, that I have to build some sort of scaffolding to reach them to clear to open skies again.

FYI: I think Miners Advantage release 'MinersAdvantage-1.12.2-1.3.19.243.jar ' did not have this problem, meaning the radius and height limits were not as restrictive even though I had the 'common' config settings set the same for  radius of 3, and max blocks of 54.  SO I'm assuming the logic changes to fix lumbination now force it to follow the common config settings for radius and max blocks.

#### What you expected to happen:

Would like to see lumbination have it's own radius and max blocks separate config settings from shaftination, so I could set the radius larger, and it would be very helpful to have a config flag for lumbination to continue to cut down blocks until sky is reached if they are all connected wood blocks of a tree with leaves?

#### Does this issue occur on a server or single player world?

- [X ] Server
- [ ] Client Only (have not tested)

#### Versions (make sure you are on the latest version before reporting):

Minecraft Version: 1.12.2 (Thank you for continuing to update this version)
Forge Version: 14.23.5.2847
MinersAdvantage Version: MinersAdvantage-1.12.2-1.3.20.244.jar

**Comment by 0xebjc** [comment]
### TESTED:

For 'grave key' mining I have the settings set for, radius=3, max blocks=54, this lets me mine a 3x3 and 6 blocks deep in both setups below.

Using MinersAdvantage-1.12.2-1.3.20.243.jar:
- Works as expected, chopping down a tree cops as a specified lumbination radius and continues to chop the whole tree down to the top of the tree. (unless it's a giant tree above 20 or 30 blocks, haven't measured it out exactly)

Using MinersAdvantage-1.12.2-1.3.20.244.jar:
- No longer works as expected, is now bound to the settings under common, and only lumbinations a 3 block horizontal, and 6 blocks high for a max blocks of 54.

**Comment by DuelMonster** [comment]
fixed in 245
