### ISSUE TITLE
1.15.2 CultivationAgent crashes when hoe zeroes out

### ISSUE THREAD

**Issue by Knito58** [DuelMonster/MinersAdvantage#45]
#### Issue description:
Exception in server tick loop
#### What happens:
When my stone hoe reaches 0 uses then the game crashes. When restarting the level the hoe is still in main hand and has 0 uses left.
#### What you expected to happen:
The stone hoe breaks and the game continues.
#### Does this issue occur on a server or single player world?
- [dunno yet] Server
- [x] Client Only
This issue did happen in all of my worlds when starting farming. Am I really the only who has this issue? I waited if anybody else would report this. But duh.
#### Steps to reproduce:
1. Stone hoe
2. Till it away
3. Crash
#### Versions (make sure you are on the latest version before reporting):
- MinersAdvantage: 1.6.6.26
- Forge: 1.15.2 - 31.1.74
- Minecraft: 1.15.2
#### Crash log:
<details><summary>Expand for ---- Minecraft Crash Report ----</summary>
---- Minecraft Crash Report ----
// Don't do that.

Time: 06.05.20 10:05
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.item.ItemStack.func_222118_a(ItemStack.java:286) ~[?:?] {re:classloading}
	at uk.co.duelmonster.minersadvantage.workers.CultivationAgent.tick(CultivationAgent.java:71) ~[?:1.15.2-1.6.6.26] {re:classloading}
	at uk.co.duelmonster.minersadvantage.workers.AgentProcessor.fireAgentTicks(AgentProcessor.java:60) ~[?:1.15.2-1.6.6.26] {re:classloading}
	at uk.co.duelmonster.minersadvantage.events.server.ServerEventHandler.onServerTick(ServerEventHandler.java:101) ~[?:1.15.2-1.6.6.26] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_668_ServerEventHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.1.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.1.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:119) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:825) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1135423640 bytes (1082 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.1.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.74.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.74.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.74.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.74.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.74.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.74
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		CyclopsCore-1.15.2-1.6.2.jar Cyclops Core {cyclopscore@1.6.2 DONE}
		justenoughbeacons-2.0.jar Just Enough Beacons {justenoughbeacons@2.0 DONE}
		pocketstorage-1.15.2-0.5.3.jar Pocket Storage Unit {pocketstorage@1.15.2-0.5.3 DONE}
		Bettersigns-1.0_v1.15.2.jar Better Signs {bettersigns@1.0 DONE}
		rsgauges-1.15.2-1.2.3-b1.jar Gauges and Switches {rsgauges@1.2.3-b1 DONE}
		IronJetpacks-1.15.2-3.0.1.jar Iron Jetpacks {ironjetpacks@3.0.1 DONE}
		GravelMiner_1.15.1-9.0.0.jar GravelMiner {gravelminer@9.0.0 DONE}
		XaerosWorldMap_1.5.7_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.7 DONE}
		Controlling-6.1.2.jar Controlling {controlling@6.1.1 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		Powah-1.15.2-1.1.14.jar Powah {powah@1.1.14 DONE}
		NomadicTents-1.15.2-11.0.0-beta.jar Nomadic Tents {nomadictents@11.0.0-beta DONE}
		WitherSkeletonTweaks-1.15.1-4.0.0.jar Wither Skeleton Tweaks {wstweaks@4.0.0 DONE}
		Bookshelf-1.15.2-5.5.34.jar Bookshelf {bookshelf@5.5.34 DONE}
		u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 DONE}
		randompatches-1.15.2-1.21.1.2.jar RandomPatches {randompatches@1.15.2-1.21.1.2 DONE}
		buildinggadgets-3.3.5.jar Building Gadgets {buildinggadgets@3.3.5 DONE}
		DarkUtilities-1.15.2-3.0.5.jar Dark Utilities {darkutils@3.0.5 DONE}
		MysticalAgradditions-1.15.2-3.0.0.jar Mystical Agradditions {mysticalagradditions@3.0.0 DONE}
		nmdar_1.15-3.8.jar Named Areas {nmdar@3.8 DONE}
		refinedstorage-1.8.2.jar Refined Storage {refinedstorage@1.8.2 DONE}
		quartz-chests-1.1.0.5.jar Quartz Chests {quartzchests@1.1.0.5 DONE}
		AirHop-v1.2-1.15.2.jar Air Hop {airhop@1.2 DONE}
		anviltweaks-2.3.jar Anvil Tweaks {anviltweaks@2.3 DONE}
		useful_backpacks-1.15.2-1.9.4.63.jar Useful Backpacks {usefulbackpacks@1.9.4.63 DONE}
		torchmaster-2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		Lollipop-1.15.2-1.0.15.jar Lollipop {lollipop@1.0.15 DONE}
		wtbw_lib-1.15.2-1.0.18.jar WTBW Library {wtbw_lib@1.0.18 DONE}
		simplylight-1.15.2-0.9.0.jar Simply Light {simplylight@1.15.2-0.9.0 DONE}
		ferroustry-2.2.jar Ferroustry {ferroustry@2.2 DONE}
		simplybackpacks-1.15.2-1.4.3.jar Simply Backpacks {simplybackpacks@1.15.2-1.4.3 DONE}
		curios-FORGE-1.15.2-2.0.2.2.jar Curios API {curios@FORGE-1.15.2-2.0.2.2 DONE}
		camera-1.6.5.jar Camera Mod {camera@1.6.5 DONE}
		extlights-2.0.jar Extended Lights {extlights@2.0 DONE}
		ClothConfig2-2.0.jar Cloth Config Forge v2 API {cloth-config2@2.0 DONE}
		f2l-0.3.1.jar Flesh 2 Leather {f2l@0.3.1 DONE}
		xercapaint-1.15.2-2.1.jar Joy of Painting {xercapaint@1.15.2-2.1 DONE}
		lostcities-1.15-3.0.1-alpha.jar LostCities {lostcities@1.15-3.0.1-alpha DONE}
		elevatorid-1.15.2-1.7.0.jar Elevator Mod {elevatorid@1.15.2-1.7.0 DONE}
		Gobber2-1.15.2-2.2.90.jar Gobber 2 {gobber2@2.2.90 DONE}
		ChunkNoGoByeBye-1.15.2-1.2.0.jar ChunkNoGoByeBye {chunknogobyebye@1.15.2-1.2.0 DONE}
		cc-tweaked-1.15.2-1.87.0.jar CC: Tweaked {computercraft@1.87.0 DONE}
		globalxp-1.15.2-v1.4.11.jar Global XP {globalxp@v1.4.11 DONE}
		YAMDA-5.0.1.jar YAMDA {yamda@5.0.1 DONE}
		classicbar-3.0.2.jar Classic Bar {classicbar@3.0.2 DONE}
		CleanView-1.15.2-v1.jar CleanView {cleanview@1.15.2-v1 DONE}
		QuantumStorage-1.15.2-5.1.0.jar QuantumStorage {quantumstorage@NONE DONE}
		Cyclic-1.15.2-0.4.1.jar Cyclic {cyclic@1.15.2-0.4.1 DONE}
		cullparticles-1.0.jar Cull Particles {cullparticles@1.0 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		resynth-4.1.0.jar Resynth {resynth@4.1.0 DONE}
		Ma-Enchants-1.15.1-1.7.0.jar Ma Enchants {ma-enchants@1.15.1-1.7.0 DONE}
		Cucumber-1.15.2-3.0.5.jar Cucumber Library {cucumber@3.0.5 DONE}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		metalbarrels-2.1.jar Metal Barrels {metalbarrels@2.1 DONE}
		longfallboots-1.4.0b.jar Long Fall Boots {longfallboots@1.4.0b DONE}
		EverlastingAbilities-1.15.2-1.6.1.jar EverlastingAbilities {everlastingabilities@1.6.1 DONE}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 DONE}
		fablibrary-1.15.2-1.1.jar FAB Library {fablibrary@1.1 DONE}
		Waystones_1.15.2-6.0.0.jar Waystones {waystones@6.0.0 DONE}
		LightOverlay-4.2.jar Light Overlay Forge {lightoverlay-forge@4.2 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		SimpleStorageNetwork-1.15.2-0.3.0.jar Simple Storage Network {storagenetwork@1.15.2-0.3.0 DONE}
		BotanyPots-1.15.2-2.0.14.jar BotanyPots {botanypots@2.0.14 DONE}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		mcjtylib-1.15-4.0.3-alpha.jar McJtyLib {mcjtylib@1.15-4.0.3-alpha DONE}
		rftoolsbase-1.15-1.0.1-alpha.jar RFToolsBase {rftoolsbase@1.15-1.0.1-alpha DONE}
		xnet-1.15-2.0.2-alpha.jar XNet {xnet@1.15-2.0.2-alpha DONE}
		rftoolsstorage-1.15-1.0.3-alpha.jar RFToolsStorage {rftoolsstorage@1.15-1.0.3-alpha DONE}
		ClickMachine-1.15.2-3.0.2.jar Click Machine {clickmachine@3.0.2 DONE}
		travellersboots-1.15.2-1.3.2.jar Traveller's Boots {travellersboots@1.3.1 DONE}
		Crafting+Spawn-1.15.2.0.2.1.jar Crafting Spawn {craftingspawn@0.2.1 DONE}
		endercompass-2.0.jar Ender Compass {endercompass@2.0 DONE}
		CraftTweaker-1.15.2-6.0.0.23.jar CraftTweaker {crafttweaker@6.0.0.23 DONE}
		rftoolspower-1.15-2.0.1-alpha.jar RFToolsPower {rftoolspower@1.15-2.0.1-alpha DONE}
		forge-1.15.2-31.1.74-universal.jar Forge {forge@31.1.74 DONE}
		wtbw_core-1.15.2-1.0.13.jar WTBW Core {wtbw_core@1.0.13 DONE}
		wtbw_tools-1.15.2-1.0.13.jar WTBW Tools {wtbw_tools@1.0.13 DONE}
		ColossalChests-1.15.2-1.7.7.jar ColossalChests {colossalchests@1.7.7 DONE}
		MysticalAgriculture-1.15.2-3.0.2.jar Mystical Agriculture {mysticalagriculture@3.0.2 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		MinersAdvantage-1.15.2-1.6.6.26.jar MinersAdvantage {minersadvantage@1.15.2-1.6.6.26 DONE}
		forge-1.15.2-31.1.74-client.jar Minecraft {minecraft@1.15.2 DONE}
		rftoolsutility-1.15-2.0.1-alpha.jar RFToolsUtility {rftoolsutility@1.15-2.0.1-alpha DONE}
		nbttooltips-2.0.jar NBT Tooltips {nbttooltips@2.0 DONE}
		EnchantmentDescriptions-1.15.2-2.0.8.jar EnchantmentDescriptions {enchdesc@2.0.8 DONE}
		theoneprobe-1.15-2.0.2.jar The One Probe {theoneprobe@1.15-2.0.2 DONE}
		playerplates-1.15-forge-1.0.0.jar Player Plates {playerplates@1.15-forge-1.0.0 DONE}
		useful_railroads-1.15.2-1.3.1.20.jar Useful Railroads {usefulrailroads@1.3.1.20 DONE}
		wtbw_machines-1.15.2-1.0.21.jar WTBW Machines {wtbw_machines@1.0.21 DONE}
		spiketraps-2.0.jar Spike Traps {spiketraps@2.0 DONE}
		rftoolsbuilder-1.15-2.0.1-alpha.jar RFToolsBuilder {rftoolsbuilder@1.15-2.0.1-alpha DONE}
		Xaeros_Minimap_20.8.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.8.0 DONE}
		wtbw_decoration-1.15.2-1.0.11.jar WTBW Decoration {wtbw_decoration@1.0.11 DONE}
		gravestone-1.17.4.jar Gravestone Mod {gravestone@1.17.4 DONE}
		cyclepaintings_1.15-1.2.jar Cycle Paintings {cyclepaintings@1.2 DONE}
		corail_recycler-4.0.4-1.15.2.jar Corail Recycler {corail_recycler@4.0.4 DONE}
		DoubleSlabs-1.15-2.2.5.jar Double Slabs {doubleslabs@2.2.5 DONE}
		tubesreloaded-1.15.2-1.3.0c.jar Tubes Reloaded {tubesreloaded@1.15.2-1.3.0c DONE}
		acceleratorcraft-1.2.jar AcceleratorCraft {acceleratorcraft@1.2 DONE}
		InstantLava_1.13.2-1.1.1.jar InstantLava {instantlava@1.1.1 DONE}
		[1.15.1-1.15.2]TorchBowMod_v1.4.jar TorchBowMod {torchbowmod@1.4 DONE}
		mobcatcher-2.2.jar Mob Catcher {mobcatcher@2.2 DONE}
		engineersdecor-1.15.2-1.0.20-b6.jar Engineer's Decor {engineersdecor@1.0.20-b6 DONE}
		RefinedRelocation_1.15.2-7.1.1.jar Refined Relocation {refinedrelocation@7.1.1 DONE}
		moredragoneggs-1.0.jar More Dragon Eggs {moredragoneggs@1.0 DONE}
		CloudBoots-1.15.2-2.0.0.jar Cloud Boots Mod {cloudboots@2.0.0 DONE}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 DONE}
		Ma-Essentials-1.15.2-3.0.2.jar Ma Essentials {ma-essentials@1.15.2-3.0.2 DONE}
		healingcf_1.15-2.1.jar Healing Campfire {healingcf@2.1 DONE}
		draw_bridge-1.15.2-1.4.3.18.jar Draw Bridge {drawbridge@1.4.3.18 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['Konitor'/234, l='NewWorld', x=-177.16, y=73.94, z=181.08]]
	Data Packs: vanilla, mod:cyclopscore (incompatible), mod:justenoughbeacons (incompatible), mod:pocketstorage (incompatible), mod:bettersigns (incompatible), mod:rsgauges, mod:ironjetpacks, mod:gravelminer (incompatible), mod:xaeroworldmap, mod:controlling (incompatible), mod:placebo (incompatible), mod:powah (incompatible), mod:nomadictents (incompatible), mod:wstweaks (incompatible), mod:bookshelf (incompatible), mod:uteamcore, mod:randompatches (incompatible), mod:buildinggadgets (incompatible), mod:darkutils (incompatible), mod:mysticalagradditions, mod:nmdar (incompatible), mod:refinedstorage (incompatible), mod:quartzchests (incompatible), mod:airhop, mod:anviltweaks (incompatible), mod:usefulbackpacks, mod:torchmaster (incompatible), mod:phosphor, mod:lollipop (incompatible), mod:wtbw_lib, mod:simplylight (incompatible), mod:ferroustry (incompatible), mod:simplybackpacks (incompatible), mod:curios (incompatible), mod:camera, mod:extlights, mod:cloth-config2 (incompatible), mod:f2l, mod:xercapaint (incompatible), mod:lostcities (incompatible), mod:elevatorid, mod:gobber2 (incompatible), mod:chunknogobyebye, mod:computercraft (incompatible), mod:globalxp (incompatible), mod:yamda (incompatible), mod:classicbar (incompatible), mod:cleanview (incompatible), mod:quantumstorage (incompatible), mod:cyclic (incompatible), mod:cullparticles (incompatible), mod:inventorysorter (incompatible), mod:resynth (incompatible), mod:ma-enchants (incompatible), mod:cucumber, mod:trashslot (incompatible), mod:jei (incompatible), mod:metalbarrels (incompatible), mod:longfallboots (incompatible), mod:everlastingabilities (incompatible), mod:attributefix (incompatible), mod:fablibrary (incompatible), mod:waystones (incompatible), mod:lightoverlay-forge (incompatible), mod:naturescompass (incompatible), mod:storagenetwork (incompatible), mod:botanypots (incompatible), mod:dungeoncrawl (incompatible), mod:mcjtylib (incompatible), mod:rftoolsbase (incompatible), mod:xnet (incompatible), mod:rftoolsstorage (incompatible), mod:clickmachine (incompatible), mod:travellersboots (incompatible), mod:craftingspawn (incompatible), mod:endercompass (incompatible), mod:crafttweaker (incompatible), mod:rftoolspower (incompatible), mod:forge (incompatible), mod:wtbw_core, mod:wtbw_tools, mod:colossalchests (incompatible), mod:mysticalagriculture, mod:ironchest, mod:minersadvantage (incompatible), mod:rftoolsutility (incompatible), mod:nbttooltips (incompatible), mod:enchdesc (incompatible), mod:theoneprobe (incompatible), mod:playerplates (incompatible), mod:usefulrailroads, mod:wtbw_machines, mod:spiketraps, mod:rftoolsbuilder (incompatible), mod:xaerominimap, mod:wtbw_decoration, mod:gravestone, mod:cyclepaintings (incompatible), mod:corail_recycler, mod:doubleslabs, mod:tubesreloaded (incompatible), mod:acceleratorcraft, mod:instantlava (incompatible), mod:torchbowmod (incompatible), mod:mobcatcher (incompatible), mod:engineersdecor, mod:refinedrelocation (incompatible), mod:moredragoneggs, mod:cloudboots, mod:refinedstorageaddons (incompatible), mod:ma-essentials (incompatible), mod:healingcf (incompatible), mod:drawbridge
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
</details>

**Comment by MFTTFM** [comment]
I encountered a similar bug, game crashed after digging many times, but I won't crashed when my hoe brocken. I played in a single player world with skyblock, as we know we need it to get more dirt. More seriously, I can't close it with keypad 8 either. It seems like crashed by some strange process not closing.(Unprofessional)

Versions:
MinersAdvantage-1.15.2-1.6.7.29
Forge: 1.15.2 - 31.2.9

<details>
<summary>Crash log:</summary>

---- Minecraft Crash Report ----
// You're mean.

Time: 20-7-3 上午10:59
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.item.ItemStack.func_222118_a(ItemStack.java:286) ~[?:?] {re:classloading}
	at uk.co.duelmonster.minersadvantage.workers.CultivationAgent.tick(CultivationAgent.java:71) ~[?:1.15.2-1.6.7.29] {re:classloading}
	at uk.co.duelmonster.minersadvantage.workers.AgentProcessor.fireAgentTicks(AgentProcessor.java:60) ~[?:1.15.2-1.6.7.29] {re:classloading}
	at uk.co.duelmonster.minersadvantage.events.server.ServerEventHandler.onServerTick(ServerEventHandler.java:101) ~[?:1.15.2-1.6.7.29] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_54_ServerEventHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:119) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:825) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3396338496 bytes (3239 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.9
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.9-client.jar Minecraft {minecraft@1.15.2 DONE}
		FallingTree-1.15.2-2.0.3+19.jar Falling Tree {falling_tree@2.0.3+19 DONE}
		forgemod_VoxelMap-1.9.19_for_1.15.2.jar VoxelMap {voxelmap@1.9.19 DONE}
		forge-1.15.2-31.2.9-universal.jar Forge {forge@31.2.9 DONE}
		inventoryprofiles-forge-1.15.2-0.2.1.jar Inventory Profiles {inventoryprofiles@0.2.1 DONE}
		Neat+1.6-22.jar Neat {neat@1.6-22 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		MinersAdvantage-1.15.2-1.6.7.29.jar MinersAdvantage {minersadvantage@1.15.2-1.6.7.29 DONE}
		mod_autofish_forge-1.15.2-1.7.jar AutoFish Forge Mod {mod_autofish@1.15.2-1.7 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['mofeite'/160, l='Skyblock 4.07', x=-7.21, y=61.94, z=2.54]]
	Data Packs: mod:falling_tree, mod:voxelmap, mod:forge (incompatible), mod:inventoryprofiles (incompatible), mod:neat (incompatible), mod:appleskin (incompatible), mod:minersadvantage (incompatible), mod:mod_autofish (incompatible), vanilla, file/skyblockDatapack (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
</details>
