### ISSUE TITLE
Just downloaded MA, can't configure?

### ISSUE THREAD

**Issue by Ree486** [DuelMonster/MinersAdvantage#50]
When I go to configure MinersAdvantage in the mods section of the menu, the Config button is  greyed out and cannot be selected. This may be because it is the first mod I have ever downloaded, but I have no idea what I could have done wrong or how to fix it. I've redownloaded the file, relaunched Minecraft, and even restarted my computer, all to no avail. I know the mod is running because I tested the Lumbination, which worked. I just don't know how or where to configure the mod.

- [ ] Server
- [x] Client Only

1. Download MinersAdvantage
2. Launch Minecraft w Forge
3. Click Mods button on main screen
4. Suffer

- MinersAdvantage: 1.15.2-1.6.7.29
- Forge: 31.2.0
- Minecraft: 1.15.2

**Comment by DuelMonster** [comment]
Currently you will need to modify the config manually.  I am looking into a possible solution.

config\minersadvantage-client.toml

**Comment by DuelMonster** [comment]
GUI config has now been added and can be accessed while in game with default key bind of CTRL+INSERT

**Comment by Pool-E** [comment]
> GUI config has now been added and can be accessed while in game with default key bind of CTRL+INSERT

I still can't open it with CTRL+INSERT
