### ISSUE TITLE
Feature Request:  Click Mining Fix

### ISSUE THREAD

**Issue by budgej** [DuelMonster/MinersAdvantage#53]
[Click Mining Fix](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1276978-1-6-2-click-mining-fix-fix-speed-up-all-mining)

I've been hooked on this very small patch for years.  Haven't found a version for 1.15.2 however, and it has always required patching the Minecraft jar.  Would be very nice if it were included in your mod!

**Comment by DuelMonster** [comment]
Doesn't fit with my mods focus
