### ISSUE TITLE
Not Working On Custom Server

### ISSUE THREAD

**Issue by ForgottenLmGz** [DuelMonster/MinersAdvantage#59]
Not working on my custom server I host from my pc. No clue what everything in the screenshot means.
- [x ] Server
- [ ] Client Only

#### Steps to reproduce:
1. 
![minecraftminersadvabtage](https://user-images.githubusercontent.com/73374977/97067183-941f2b80-1580-11eb-8b1b-9350bc715c5d.PNG)

2. 
3. 

#### Versions (make sure you are on the latest version before reporting):

- MinersAdvantage:1.16.3
- Forge:1.16.3
- Minecraft:1.16.3

#### Crash log:

<details><summary>Expand for ---- Minecraft Crash Report ----</summary>

```
PASTE_HERE
```
</details>

**Comment by grokkingit** [comment]
Can confirm. I'm getting the same crash on startup on Ubuntu with a dedicated server with no other mods loaded.

- MinersAdvantage: 1.16.3-1.7.5.160
- Forge: 1.16.3-34.1.25

**Comment by OlasHSW** [comment]
I have the same issue. On server on my pc and on server on hosting website. I have installed only this one mod.

- MinersAdvantage-1.16.4-1.8.0.174
- Forge-1.16.4-35.1.7

**Comment by asheath** [comment]
Wow did not realize this issue is old...
Same problem, I tried removing all mods except MinersAdvantage and still wouldn't work, it works fine in singleplayer/client but not in dedicated server.
MinersAdvantage-1.16.4-1.8.0.174
Forge-1.16.4-35.1.13
