### ISSUE TITLE
Illumination puts torch on every digged block regardless of light level

### ISSUE THREAD

**Issue by Knito58** [DuelMonster/MinersAdvantage#6]
#### Issue description:
When digging a shaft a torch is placed at every step

#### What happens:

What I said :). The light level is not taken into account.

#### What you expected to happen:

Torch is placed at confgured "lowest light level".

#### Does this issue occur on a server or single player world?

- [ dont know ] Server
- [ X  ] Client Only

#### Steps to reproduce:
1.  Illumination on
2. Have torches
3. Dig a shaft

#### Versions (make sure you are on the latest version before reporting):

- MinersAdvantage:  1.3.14.189
- Forge: 14.23.2.2654
- Minecraft: 1.12.2

#### Crash log:

No crash no log :)

**Comment by DuelMonster** [comment]
Could you please retry after updating forge to the current recommended version 14.23.3.2655

Thanks

**Comment by Knito58** [comment]
Forge Version 14.23.3.2666: Same error. Even in the brightest place, when I hit a block then a torch is placed. A shaft = a line full of torches placed one after the other.

**Comment by DuelMonster** [comment]
OK I'll take a look at it tonight. Thnx

**Comment by DuelMonster** [comment]
@Knito58 I'm now wondering whether this issue may be related to GravelMiner also...
Would u mind removing/disabling GravelMiner and trying again?  Thanks

**Comment by Knito58** [comment]
Sorry. Now I have the recommended Forge 14.23.3.2655 and the error persists. Maybe I configured st wrongly in the Illumination section?

Illu enabled = true
use block light level = false
lowest light level = 4

**Comment by DuelMonster** [comment]
AH, yes, without the "use block light level" being true MA uses the Sky light level.
